### PR TITLE
Libs

### PR DESCRIPTION
**Pull request by designatednerd**

### CODE REVIEW

**Comment by designatednerd** [comment]
@vokal/webandsystems Hey look some libraries! Who wants to do a "code review"?

**Comment by StoicJester** [comment]
usually we use bower to install libraries, so we don't have to store them on a repo, but that may be a non-hack day project

**Comment by designatednerd** [comment]
Yes, i mentioned in my last PR that after hack days I'm going to talk to you guys about better ways to do all this.

**Comment by scottferg** [comment]
You're including stuff like a pro. LGTM but yeah, highly recommended you switch to bower later on. Basically Cocoapods for the web.

**Comment by designatednerd** [comment]
@scottferg I'm not sure that's as much of a selling point as you think it is.

**Comment by scottferg** [comment]
Oh sorry, I meant to say: Basically Cocoapods for the web except it works incredibly well

**Pull request merged**
